[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[dev]
  framework = "vite"
  port = 8888
  functions = "netlify/functions"

[context.dev.environment]
  NVD_API_KEY = "5e0fcab5-8993-4912-927a-1b6128fbc755"  

[[redirects]]
  from = "/api/threats"
  to = "/.netlify/functions/get-threats"
  status = 200
  force = true

[build.environment]
  NETLIFY_EXPERIMENTAL_WARM_LAMBDA = "true"